FROM dunglas/frankenphp:php8.4

WORKDIR /app

COPY . /app

RUN install-php-extensions pdo_mysql mysqli

ENV SERVER_NAME=:80

EXPOSE 80

CMD ["frankenphp", "php-server", "--root", "/app", "--listen", ":80"]